### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by LifeiBanana** [claroche-r/DMBSR#1]
Hello, when I reproduced your thesis, I found that a file was missing: kernels/custom_blur_centered.mat.
Is it convenient to provide this file?

**Comment by claroche-r** [comment]
Hi @LifeiBanana ,

You are right, we did not include the file "custom_blur_centered.mat" since it was too big.
The file contains a blur kernel dataset built using this [paper](https://ieeexplore.ieee.org/document/6127172).

Here is the Google drive link to download the dataset: https://drive.google.com/file/d/1fDtSwItCCqob6ZJ_zvVfvQJ8U1q7dV7D/view?usp=share_link

You can also degrade your images using your own blur kernels if needed.

Thanks for your interest,
Charles
