### ISSUE TITLE
flip kernel when do the convolution.

### ISSUE THREAD

**Issue by tuvovan** [claroche-r/DMBSR#4]
Hello,

I just noticed that you flip the blur kernel in the `convolve_tensor` function and do not do that in `cross_correlate_tensor`. May I know the reason behind this?

Thank you!

**Comment by claroche-r** [comment]
Hello,

In PyTorch, the function torch.nn.functional.conv2d() implements a cross correlation between the input and the kernel not a convolution as the name would suggest. To implement a convolution, one just need to flip the blur kernel.

I also need to have a cross-correlation function in the code since I need both the operator H (a convolution) and its transpose $H^T$ (a cross correlation) to implement the model.

**Comment by tuvovan** [comment]
then the main difference between cross-correlation and convolution is flip and not flip right?

**Comment by claroche-r** [comment]
Yes, the operation is the same but the filter is flipped.

**Comment by tuvovan** [comment]
thanks!
